# Generated by Django 5.2.13 on 2026-05-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-data_evento'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='data_hora',
            new_name='data_evento',
        ),
    ]
