# Generated by Django 5.2.13 on 2026-05-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao',
            name='endereco',
        ),
    ]
