# Generated by Django 5.2.13 on 2026-05-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0002_remove_doacao_endereco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doacao',
            options={'verbose_name': 'Doação', 'verbose_name_plural': 'Doações'},
        ),
    ]
