# Generated by Django 5.2.13 on 2026-05-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='voluntarios',
            name='area_interesse',
        ),
        migrations.AddField(
            model_name='voluntarios',
            name='area_interesse',
            field=models.ManyToManyField(to='voluntarios.areainteresse'),
        ),
    ]
