# Generated by Django 5.2.13 on 2026-05-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0002_areainteresse_remove_voluntarios_area_interesse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voluntarios',
            options={'verbose_name': 'Voluntário', 'verbose_name_plural': 'Voluntários'},
        ),
    ]
